### ISSUE TITLE
How to compile this kind of project

### ISSUE THREAD

**Issue by elyphas** [cornerman/mycelium#204]
Sorry if this is not appropiate.

But I am trying to understand the code of mycelium hoping to understand where the error comes from :-)

I am trying to compile the project in my machine, but I get and error.

`sbt compile`

```scala
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.13)
[info] loading global plugins from /home/elyphas/.sbt/1.0/plugins
[info] loading settings for project mycelium-0-2-0-build from plugins.sbt ...
[info] loading project definition from /home/elyphas/quitar/mycelium-0.2.0/project
[info] loading settings for project root from build.sbt ...
[info] set current project to mycelium-root (in build file:/home/elyphas/quitar/mycelium-0.2.0/)
[info] Executing in batch mode. For better performance use sbt's shell
[error] java.util.NoSuchElementException: None.get
[error] 	at scala.None$.get(Option.scala:529)
[error] 	at scala.None$.get(Option.scala:527)
[error] 	at $e2c734d536842b9844de$.$anonfun$jsSettings$1(build.sbt:43)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] java.util.NoSuchElementException: None.get
[error] 	at scala.None$.get(Option.scala:529)
[error] 	at scala.None$.get(Option.scala:527)
[error] 	at $e2c734d536842b9844de$.$anonfun$jsSettings$1(build.sbt:43)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (coreJS / scalacOptions) java.util.NoSuchElementException: None.get
[error] (clientJS / scalacOptions) java.util.NoSuchElementException: None.get
[error] Total time: 2 s, completed 20 nov 2022 17:21:45
```
I also tried from the shell of sbt:

```scala

sbt:mycelium-root> clientJS/compile

[error] stack trace is suppressed; run last coreJS / scalacOptions for the full output
[error] stack trace is suppressed; run last clientJS / scalacOptions for the full output
[error] (coreJS / scalacOptions) java.util.NoSuchElementException: None.get
[error] (clientJS / scalacOptions) java.util.NoSuchElementException: None.get
[error] Total time: 3 s, completed 20 nov 2022 17:24:33
```

**Comment by elyphas** [comment]
```scala
sbt:mycelium-root> project clientJS
[info] set current project to mycelium-client-js (in build file:/home/elyphas/quitar/mycelium-0.2.0/)
sbt:mycelium-client-js> compile
[error] stack trace is suppressed; run last coreJS / scalacOptions for the full output
[error] stack trace is suppressed; run last scalacOptions for the full output
[error] (coreJS / scalacOptions) java.util.NoSuchElementException: None.get
[error] (scalacOptions) java.util.NoSuchElementException: None.get
[error] Total time: 2 s, completed 20 nov 2022 17:37:49
```

**Comment by elyphas** [comment]
done
